version: '3'

services:
  xss-demo-database:
    image: 'mysql:5'
    container_name: sql-database
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=password1234
      - MYSQL_DATABASE=xss_db
      - MYSQL_USER=xss_db_user
      - MYSQL_PASSWORD=password1234
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'

  xss-demo-web:
    build: .
    image: xss-apache
    container_name: web
    volumes:
      - './html/:/var/www/html/'
    ports:
      - '80:80'
